services:
    Randock\DddBundle\Middleware\TranslationMiddleware:
        class: Randock\DddBundle\Middleware\TranslationMiddleware
        arguments:
          - '@translator'
          - 'messages'

    Randock\DddBundle\Middleware\CacheMiddleware:
        class: Randock\DddBundle\Middleware\CacheMiddleware
        arguments:
          - '@randock_ddd.command_cache_service'
